coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
        base: auto
    patch:
      default:
        target: 70%
        threshold: 5%

  ignore:
    - "tests/"
    - "setup.py"
    - "examples/"
    - "**/conftest.py"

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false
  require_base: no
  require_head: yes

github_checks:
  annotations: true