name: 🐛 Bug Report
description: File a bug report to help us improve the Puter Python SDK
title: "[BUG] "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
        Please provide as much detail as possible to help us resolve the issue quickly.

  - type: checkboxes
    id: terms
    attributes:
      label: Pre-submission Checklist
      description: Please verify these items before submitting
      options:
        - label: I have searched existing issues to ensure this isn't a duplicate
          required: true
        - label: I have read the documentation and tried the suggested solutions
          required: true
        - label: I am using the latest version of the Puter Python SDK
          required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug you encountered...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to reproduce the behavior
      placeholder: |
        1. Import the library with '...'
        2. Call function '...'
        3. Pass parameters '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what you expected to happen...
    validations:
      required: true

  - type: textarea
    id: actual-behavior
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: textarea
    id: error-logs
    attributes:
      label: Error Messages/Logs
      description: If applicable, add error messages or logs
      render: shell
      placeholder: Paste error messages or logs here...

  - type: dropdown
    id: python-version
    attributes:
      label: Python Version
      description: What version of Python are you using?
      options:
        - Python 3.8
        - Python 3.9
        - Python 3.10
        - Python 3.11
        - Python 3.12
        - Other (specify in additional context)
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu)
        - Linux (Other)
        - Other (specify in additional context)
    validations:
      required: true

  - type: input
    id: sdk-version
    attributes:
      label: SDK Version
      description: What version of the Puter Python SDK are you using?
      placeholder: e.g., 0.4.0
    validations:
      required: true

  - type: textarea
    id: code-sample
    attributes:
      label: Minimal Code Sample
      description: Please provide a minimal code sample that reproduces the issue
      render: python
      placeholder: |
        from puter import PuterAI

        client = PuterAI(username="...", password="...")
        # Your code that reproduces the issue
    validations:
      required: false

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Low - Minor inconvenience
        - Medium - Affects functionality but has workaround
        - High - Breaks important functionality
        - Critical - Completely unusable
    validations:
      required: true
