name: Auto Assign and Label

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
    - name: Auto assign issues and PRs
      uses: actions/github-script@v6
      with:
        script: |
          const issue = context.payload.issue || context.payload.pull_request;
          const isIssue = !!context.payload.issue;
          const isPR = !!context.payload.pull_request;
          
          // Auto-assign based on content
          let assignees = [];
          let labels = [];
          
          const title = issue.title.toLowerCase();
          const body = (issue.body || '').toLowerCase();
          const content = title + ' ' + body;
          
          // Determine labels based on content
          if (content.includes('bug') || content.includes('error') || content.includes('issue')) {
            labels.push('bug');
          }
          
          if (content.includes('feature') || content.includes('enhancement') || content.includes('new')) {
            labels.push('enhancement');
          }
          
          if (content.includes('doc') || content.includes('readme') || content.includes('documentation')) {
            labels.push('documentation');
          }
          
          if (content.includes('test') || content.includes('testing')) {
            labels.push('testing');
          }
          
          if (content.includes('security') || content.includes('vulnerability')) {
            labels.push('security');
            labels.push('priority-high');
          }
          
          if (content.includes('performance') || content.includes('optimization')) {
            labels.push('performance');
          }
          
          if (content.includes('ci') || content.includes('github action') || content.includes('workflow')) {
            labels.push('ci/cd');
          }
          
          // Set priority labels
          if (content.includes('critical') || content.includes('urgent')) {
            labels.push('priority-critical');
          } else if (content.includes('high priority') || content.includes('important')) {
            labels.push('priority-high');
          } else if (content.includes('low priority') || content.includes('minor')) {
            labels.push('priority-low');
          } else {
            labels.push('priority-medium');
          }
          
          // Add type labels
          if (isIssue) {
            labels.push('issue');
          } else if (isPR) {
            labels.push('pull-request');
            
            // Additional PR labels
            if (title.includes('fix') || title.includes('bug')) {
              labels.push('bugfix');
            }
            
            if (title.includes('feat') || title.includes('feature')) {
              labels.push('feature');
            }
            
            if (title.includes('docs') || title.includes('documentation')) {
              labels.push('documentation');
            }
            
            if (title.includes('refactor')) {
              labels.push('refactoring');
            }
            
            if (title.includes('test')) {
              labels.push('testing');
            }
            
            if (title.includes('chore') || title.includes('deps') || title.includes('dependency')) {
              labels.push('maintenance');
            }
          }
          
          // Apply labels
          if (labels.length > 0) {
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              labels: labels
            });
          }
          
          // Add welcome comment for first-time contributors
          const author = issue.user.login;
          
          // Check if this is the user's first contribution
          const contributions = await github.rest.repos.listCommits({
            owner: context.repo.owner,
            repo: context.repo.repo,
            author: author,
            per_page: 1
          });
          
          const isFirstContribution = contributions.data.length === 0;
          
          if (isFirstContribution && isPR) {
            const welcomeMessage = `
            🎉 **Welcome to the Puter Python SDK!** 
            
            Thank you for your first contribution! We appreciate you taking the time to improve our project.
            
            ### What happens next?
            
            1. ✅ Our automated tests will run on your PR
            2. 👀 A maintainer will review your changes
            3. 💬 We may provide feedback or suggestions
            4. 🚀 Once approved, your changes will be merged!
            
            ### Guidelines
            
            - Make sure all tests pass
            - Follow our coding standards
            - Update documentation if needed
            - Be responsive to feedback
            
            Feel free to ask questions in the comments if you need any help!
            
            ---
            
            *This message was automatically generated.*
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: welcomeMessage
            });
          }
          
          if (isFirstContribution && isIssue) {
            const welcomeMessage = `
            👋 **Welcome to the Puter Python SDK!**
            
            Thank you for reporting this issue! We appreciate community feedback to help improve our project.
            
            ### What happens next?
            
            1. 🏷️ We've automatically labeled your issue
            2. 👀 A maintainer will triage and respond
            3. 🔍 We may ask for additional information
            4. 🛠️ We'll work on addressing the issue
            
            ### To help us help you
            
            Please make sure you've included:
            - [ ] Clear description of the issue
            - [ ] Steps to reproduce (if applicable)
            - [ ] Expected vs actual behavior
            - [ ] Environment details (Python version, OS, etc.)
            - [ ] Relevant code snippets or error messages
            
            ---
            
            *This message was automatically generated.*
            `;
            
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.number,
              body: welcomeMessage
            });
          }

  stale-issue-management:
    runs-on: ubuntu-latest
    if: github.event_name == 'schedule'
    steps:
    - name: Close stale issues and PRs
      uses: actions/stale@v8
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: |
          This issue has been automatically marked as stale because it has not had recent activity. 
          It will be closed if no further activity occurs. Thank you for your contributions!
          
          If you believe this issue is still relevant, please:
          - Add a comment explaining why it should remain open
          - Provide any additional context or updates
          - Remove the 'stale' label
        stale-pr-message: |
          This pull request has been automatically marked as stale because it has not had recent activity.
          It will be closed if no further activity occurs. Thank you for your contributions!
          
          If you want to continue with this PR, please:
          - Rebase your branch with the latest changes
          - Address any requested changes
          - Add a comment to indicate you're still working on it
          - Remove the 'stale' label
        close-issue-message: |
          This issue was closed because it has been stale for 30 days with no activity.
          If you believe this was closed in error, please reopen it and provide the requested information.
        close-pr-message: |
          This pull request was closed because it has been stale for 30 days with no activity.
          If you want to continue with this PR, please reopen it and address any feedback.
        days-before-stale: 30
        days-before-close: 7
        stale-issue-label: 'stale'
        stale-pr-label: 'stale'
        exempt-issue-labels: 'priority-high,priority-critical,security,pinned'
        exempt-pr-labels: 'priority-high,priority-critical,security,pinned'